### ISSUE TITLE
[IAM] Remove login_protection not possible.

### ISSUE THREAD

**Issue by dibi-codes** [opentelekomcloud/terraform-provider-opentelekomcloud#2440]
# Terraform provider version
v1.36.1

# Affected Resource(s)
`opentelekomcloud_identity_user_v3`

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_identity_user_v3" "user" {
  name        = "username"
  enabled     = true
  access_type = "programmatic"
  description = "Description"
}
```

# Debug Output/Panic Output
```
opentelekomcloud_identity_user_v3.user: Modifying... [id=ef3ef5f8ed104b6e83bc064f1XXXX]
╷
│ Error: Plugin did not respond
│
│   with opentelekomcloud_identity_user_v3.user,
│   on iam.tf line 1, in resource "opentelekomcloud_identity_user_v3" "user":
│    1: resource "opentelekomcloud_identity_user_v3" "user" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.

Stack trace from the terraform-provider-opentelekomcloud_v1.36.1 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 94 [running]:
github.com/opentelekomcloud/terraform-provider-opentelekomcloud/opentelekomcloud/services/iam.resourceIdentityUserV3Update({0x105d75fa8, 0x140009f4240}, 0x14000933780, {0x105d58180?, 0x14000593dc0?})
        github.com/opentelekomcloud/terraform-provider-opentelekomcloud/opentelekomcloud/services/iam/resource_opentelekomcloud_identity_user_v3.go:307 +0x9d4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x14000545880, {0x105d75fe0, 0x1400094e120}, 0xd?, {0x105d58180, 0x14000593dc0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:741 +0xe8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000545880, {0x105d75fe0, 0x1400094e120}, 0x1400057d1e0, 0x14000933600, {0x105d58180, 0x14000593dc0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:847 +0x68c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400019ad50, {0x105d75fe0?, 0x1400094e000?}, 0x140008f3ea0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xb78
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x1400041da40, {0x105d75fe0?, 0x140008cf6e0?}, 0x140003af180)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:818 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x105cf80e0?, 0x1400041da40}, {0x105d75fe0, 0x140008cf6e0}, 0x140003af0a0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140001ba000, {0x105d7b580, 0x14000702d00}, 0x140008a1560, 0x14000781bc0, 0x10665ff60, 0x0)
        google.golang.org/grpc@v1.56.3/server.go:1335 +0xc90
google.golang.org/grpc.(*Server).handleStream(0x140001ba000, {0x105d7b580, 0x14000702d00}, 0x140008a1560, 0x0)
        google.golang.org/grpc@v1.56.3/server.go:1712 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.56.3/server.go:947 +0xb4
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.56.3/server.go:958 +0x174
panic: runtime error: index out of range [0] with length 0
```

# Steps to Reproduce
We've got a user which has a disabled `login_protection` but, after the upgrade to 1.36.1, TF wants to remove those fields.
1. `terraform plan`
   The plan states it wants to remove the `login_protection` object. (Which should be optional?!)
2. `terraform apply`
   The apply results in the given exception.

# Expected Behavior
The user should have `login_protection` removed and the protection should be/stay disabled on otc side.

# Actual Behavior
Above exception

**Comment by artem-lifshits** [comment]
Hello @dabeck fixed in latest release, please check.

**Comment by dibi-codes** [comment]
Yes, looking good. thank you.
